### ISSUE TITLE
Request support for RKE

### ISSUE THREAD

**Issue by rdcarrera** [nutanix/helm#11]
Hi everyone!

I was fighting to deploy the nutanix csi in RKE, and after doing a lot of modification in my RKE environment:
- Use the ubuntu console
- Install within ubuntu's console the open-iscsi
- Generate a rc.local script to enable the iscsid service
- Edit the bindings of my containerized kubelet
   - '/lib/modules:/lib/modules'
   - '/etc/iscsi:/etc/iscsi'
   -  '/sbin/iscsiadm:/sbin/iscsiadm'

The last thing was modified by hand some params of the csi-node-ntnx-plugin's daemonset, 
```
....
    env:
       - name: DRIVER_REG_SOCK_PATH
          value: /opt/rke/var/lib/kubelet/plugins/com.nutanix.csi/csi.sock
....
    volumes:
      - hostPath:
          path: /opt/rke/var/lib/kubelet/plugins_registry/
          type: Directory
        name: registration-dir
      - hostPath:
          path: /opt/rke/var/lib/kubelet/plugins/com.nutanix.csi/
          type: DirectoryOrCreate
        name: plugin-dir
      - hostPath:
          path: /opt/rke/var/lib/kubelet/
          type: Directory
        name: pods-mount-dir
....
```

So, my request is the possibility to add a checkbox to automatized this modifications

P.S:
I still using ubuntu as my console, I need to create the binding of:
```
      - hostPath:
          path: /lib/x86_64-linux-gnu/libisns-nocrypto.so.0
          type: File
        name: libisns
```

**Thanks to [sike](https://forums.rancher.com/t/nutanix-csi-volume-driver/16957/2) from rancher forums**
